### ISSUE TITLE
crazynamer.com

### ISSUE THREAD

**Issue by georgekarrv** [DannyBen/php-quandl#18]
Greetings Danny, @DannyBen  a couple colleagues and I wrote a slack bot integration to hit crazynamer to give them a temporary title. It was a company favorite. Just wondering why the site was taken down, and if it’s not coming back up could you point me to the code you had for it so we can stand it up locally?

I understand this is not how to use this platform but couldn’t figure a better way to try and contact you.

**Comment by DannyBen** [comment]
Yeah, the time has come to sunset CrazyNamer.

The code is ancient PHP which is not maintainable, and I was forced to move it to another host - since WebFaction joined forced with GoDaddy.

The code is not open source, sorry.

**Comment by georgekarrv** [comment]
I appreciate the response
