### ISSUE TITLE
timeout options

### ISSUE THREAD

**Issue by brmn** [DannyBen/php-quandl#8]
There are no timeout options
neither for standard mode nor force_curl mode
php.ini has default_socket_timeout => 60 option, but sometimes getList hangs forever
strace shows nothing but "read(0," (or something similiar) in standard mode and in curl mode there is infinite poll/timeout loop

**Comment by brmn** [comment]
strace in curl mode

Process 23835 attached
restart_syscall(<... resuming interrupted call ...>) = 0
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN}], 1, 1000)  = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN}], 1, 1000)  = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN}], 1, 1000)  = 0 (Timeout)
rt_sigaction(SIGPIPE, NULL, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, 8) = 0
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN|POLLPRI|POLLRDNORM|POLLRDBAND}], 1, 0) = 0 (Timeout)
rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f1d32dffc90}, NULL, 8) = 0
poll([{fd=8, events=POLLIN}], 1, 1000^CProcess 23835 detached

**Comment by DannyBen** [comment]
Will try to add configuration for this sometime soon. If you have code snippets to set timeout for each method, this will accelerate things.

**Comment by DannyBen** [comment]
Do you have example of an API call that takes a lot of time, so I can test the timeout against it?

**Comment by DannyBen** [comment]
Hey - if you want to checkout the [dev branch](https://github.com/DannyBen/php-quandl/tree/dev) and see if the new timeout feature works as expected?

**Comment by brmn** [comment]
I do 312 getList(yahoo) requests every 2 hours to check for new tickers and update existing
just want to keep my local db up-to-date
for last three weeks there were 3-4 processes every day that hangs as described above
problem is definitely in the quandl api, but i need a method to detect it and restart the process
will check and report in few days

**Comment by DannyBen** [comment]
@brmn - is the new dev branch solving your problem?

**Comment by DannyBen** [comment]
Closing this ticket. We can revisit if there is interest.
